# GET http://localhost:3000/api/jobs
# Content-Type: application/json

# POST http://localhost:3000/api/jobs
# Content-Type: application/json

# {
#   "title": "テスト3",
#   "category": "カスタマーサポート",
#   "salary": "500"
# }

GET http://localhost:3000/api/jobs/2
Content-Type: application/json